version: "3.8"

services:
#  postgres:
#    image: postgres:17
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: ftn
#      POSTGRES_DB: DRS
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data # Trajno čuvanje podataka baze
#      - ./DataBase:/docker-entrypoint-initdb.d # Mapiranje lokalnog foldera sa init.sql
#    networks:
#      - app_network
  backend:
    build: ./Backend
    container_name: backend
    volumes:
      - ./Backend:/app              # hot-reload
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - WATCHFILES_FORCE_POLLING=true
    command: >
      flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Frontend # Folder gde se nalazi Dockerfile za frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000 # URL ka backendu
    networks:
      - app_network

volumes:
  pgdata: # Ovaj volumen je uklonjen jer više nije potreban za bazu

networks:
  app_network:
    driver: bridge # Kreira mrežu za komunikaciju između servisa