services:
  - name: postgres
    type: pserv
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: ftn
      - key: POSTGRES_DB
        value: DRS
    disk:
      name: postgres-data
      sizeGB: 10
    autoDeploy: true

  - name: backend
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python run.py"
    startCommand: "python run.py"
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgres://postgres:ftn@postgres:5432/DRS"  # URL ka bazi
    httpPort: 5000
    autoDeploy: true

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "http://backend:5000"  # URL ka backendu
    httpPort: 3000
    autoDeploy: true
